# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\designer\device_wizard\safety_limits.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WizardPageSafetyLimits(object):
    def setupUi(self, WizardPageSafetyLimits):
        WizardPageSafetyLimits.setObjectName("WizardPageSafetyLimits")
        WizardPageSafetyLimits.resize(556, 375)
        self.formLayout = QtWidgets.QFormLayout(WizardPageSafetyLimits)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(WizardPageSafetyLimits)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(WizardPageSafetyLimits)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.textBrowser = QtWidgets.QTextBrowser(WizardPageSafetyLimits)
        self.textBrowser.setObjectName("textBrowser")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.textBrowser)
        self.min_frequency_spinbox = QtWidgets.QDoubleSpinBox(WizardPageSafetyLimits)
        self.min_frequency_spinbox.setMaximum(10000.0)
        self.min_frequency_spinbox.setProperty("value", 500.0)
        self.min_frequency_spinbox.setObjectName("min_frequency_spinbox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.min_frequency_spinbox)
        self.max_frequency_spinbox = QtWidgets.QDoubleSpinBox(WizardPageSafetyLimits)
        self.max_frequency_spinbox.setMaximum(10000.0)
        self.max_frequency_spinbox.setProperty("value", 1000.0)
        self.max_frequency_spinbox.setObjectName("max_frequency_spinbox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.max_frequency_spinbox)

        self.retranslateUi(WizardPageSafetyLimits)
        QtCore.QMetaObject.connectSlotsByName(WizardPageSafetyLimits)

    def retranslateUi(self, WizardPageSafetyLimits):
        _translate = QtCore.QCoreApplication.translate
        WizardPageSafetyLimits.setWindowTitle(_translate("WizardPageSafetyLimits", "WizardPage"))
        WizardPageSafetyLimits.setTitle(_translate("WizardPageSafetyLimits", "Safety limits"))
        self.label.setText(_translate("WizardPageSafetyLimits", "Minimum frequency [Hz]"))
        self.label_2.setText(_translate("WizardPageSafetyLimits", "Maximum frequency [Hz]"))
        self.textBrowser.setHtml(_translate("WizardPageSafetyLimits", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Recommended settings for audio-based devices:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Safest: 500-1000</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Probably safe: 500-1500</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Pulse-based mode only: 500-1500+?</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Higher frequencies are less power-efficient and more likely to cause burns. </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">With the pulse-based signal generator you can generate high frequency signals with low duty cycle, which are very power-efficient. I tested signals up to 8000Hz for short periods of time without negative effects. These frequencies should absolutely not be used with continuous waveforms.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Recommended settings for 312/2B:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">For 312/2B these settings have no safety implications.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">I have been told a frequency around 100hz works best with the 312.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
