# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\designer\device_wizard\type_select.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WizardPageDeviceType(object):
    def setupUi(self, WizardPageDeviceType):
        WizardPageDeviceType.setObjectName("WizardPageDeviceType")
        WizardPageDeviceType.resize(490, 477)
        self.formLayout = QtWidgets.QFormLayout(WizardPageDeviceType)
        self.formLayout.setObjectName("formLayout")
        self.three_phase_radio = QtWidgets.QRadioButton(WizardPageDeviceType)
        self.three_phase_radio.setObjectName("three_phase_radio")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.three_phase_radio)
        self.four_phase_radio = QtWidgets.QRadioButton(WizardPageDeviceType)
        self.four_phase_radio.setObjectName("four_phase_radio")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.four_phase_radio)
        self.five_phase_radio = QtWidgets.QRadioButton(WizardPageDeviceType)
        self.five_phase_radio.setObjectName("five_phase_radio")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.five_phase_radio)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(3, QtWidgets.QFormLayout.LabelRole, spacerItem)

        self.retranslateUi(WizardPageDeviceType)
        QtCore.QMetaObject.connectSlotsByName(WizardPageDeviceType)

    def retranslateUi(self, WizardPageDeviceType):
        _translate = QtCore.QCoreApplication.translate
        WizardPageDeviceType.setWindowTitle(_translate("WizardPageDeviceType", "WizardPage"))
        WizardPageDeviceType.setTitle(_translate("WizardPageDeviceType", "Select device type"))
        self.three_phase_radio.setText(_translate("WizardPageDeviceType", "Three-phase"))
        self.four_phase_radio.setText(_translate("WizardPageDeviceType", "Four-phase (experimental)"))
        self.five_phase_radio.setText(_translate("WizardPageDeviceType", "Five-phase (experimental)"))
