# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\designer\device_wizard\waveform_select.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WizardPageWaveformType(object):
    def setupUi(self, WizardPageWaveformType):
        WizardPageWaveformType.setObjectName("WizardPageWaveformType")
        WizardPageWaveformType.resize(555, 492)
        self.verticalLayout = QtWidgets.QVBoxLayout(WizardPageWaveformType)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pulse_based_radio = QtWidgets.QRadioButton(WizardPageWaveformType)
        self.pulse_based_radio.setChecked(True)
        self.pulse_based_radio.setObjectName("pulse_based_radio")
        self.verticalLayout.addWidget(self.pulse_based_radio)
        self.label_3 = QtWidgets.QLabel(WizardPageWaveformType)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label = QtWidgets.QLabel(WizardPageWaveformType)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/restim/wizard/pulse_based.png"))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.continuous_radio = QtWidgets.QRadioButton(WizardPageWaveformType)
        self.continuous_radio.setObjectName("continuous_radio")
        self.verticalLayout.addWidget(self.continuous_radio)
        self.label_4 = QtWidgets.QLabel(WizardPageWaveformType)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_2 = QtWidgets.QLabel(WizardPageWaveformType)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/restim/wizard/continuous.png"))
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(20, 95, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(WizardPageWaveformType)
        QtCore.QMetaObject.connectSlotsByName(WizardPageWaveformType)

    def retranslateUi(self, WizardPageWaveformType):
        _translate = QtCore.QCoreApplication.translate
        WizardPageWaveformType.setWindowTitle(_translate("WizardPageWaveformType", "WizardPage"))
        WizardPageWaveformType.setTitle(_translate("WizardPageWaveformType", "Select generation algorithm"))
        self.pulse_based_radio.setText(_translate("WizardPageWaveformType", "Pulse-based"))
        self.label_3.setText(_translate("WizardPageWaveformType", "Power-efficient waveform. Slower numbing."))
        self.continuous_radio.setText(_translate("WizardPageWaveformType", "Continuous"))
        self.label_4.setText(_translate("WizardPageWaveformType", "Classic waveform. Best for 312/2B. Low power-efficiency."))
import restim_rc
