# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\designer\additionalsearchpathsdialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdditionalSearchPathsDialog(object):
    def setupUi(self, AdditionalSearchPathsDialog):
        AdditionalSearchPathsDialog.setObjectName("AdditionalSearchPathsDialog")
        AdditionalSearchPathsDialog.resize(556, 492)
        self.verticalLayout = QtWidgets.QVBoxLayout(AdditionalSearchPathsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listView = QtWidgets.QListView(AdditionalSearchPathsDialog)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)
        self.widget = QtWidgets.QWidget(AdditionalSearchPathsDialog)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_add = QtWidgets.QPushButton(self.widget)
        self.button_add.setObjectName("button_add")
        self.horizontalLayout.addWidget(self.button_add)
        self.button_remove = QtWidgets.QPushButton(self.widget)
        self.button_remove.setObjectName("button_remove")
        self.horizontalLayout.addWidget(self.button_remove)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.widget)
        self.buttonBox = QtWidgets.QDialogButtonBox(AdditionalSearchPathsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.actionAdd = QtWidgets.QAction(AdditionalSearchPathsDialog)
        self.actionAdd.setObjectName("actionAdd")
        self.actionRemove = QtWidgets.QAction(AdditionalSearchPathsDialog)
        self.actionRemove.setObjectName("actionRemove")

        self.retranslateUi(AdditionalSearchPathsDialog)
        self.buttonBox.accepted.connect(AdditionalSearchPathsDialog.accept)
        self.buttonBox.rejected.connect(AdditionalSearchPathsDialog.reject)
        self.button_add.clicked.connect(self.actionAdd.trigger)
        self.button_remove.clicked.connect(self.actionRemove.trigger)
        QtCore.QMetaObject.connectSlotsByName(AdditionalSearchPathsDialog)

    def retranslateUi(self, AdditionalSearchPathsDialog):
        _translate = QtCore.QCoreApplication.translate
        AdditionalSearchPathsDialog.setWindowTitle(_translate("AdditionalSearchPathsDialog", "Extra search paths"))
        self.button_add.setText(_translate("AdditionalSearchPathsDialog", "Add"))
        self.button_remove.setText(_translate("AdditionalSearchPathsDialog", "Remove selected"))
        self.actionAdd.setText(_translate("AdditionalSearchPathsDialog", "Add"))
        self.actionRemove.setText(_translate("AdditionalSearchPathsDialog", "Remove"))
