# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\designer\audiowritedialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AudioWriteDialog(object):
    def setupUi(self, AudioWriteDialog):
        AudioWriteDialog.setObjectName("AudioWriteDialog")
        AudioWriteDialog.resize(634, 408)
        self.verticalLayout = QtWidgets.QVBoxLayout(AudioWriteDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(AudioWriteDialog)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.groupBox = QtWidgets.QGroupBox(AudioWriteDialog)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.duration_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.duration_spinbox.setMaximum(100000.0)
        self.duration_spinbox.setObjectName("duration_spinbox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.duration_spinbox)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.file_edit = QtWidgets.QLineEdit(self.widget)
        self.file_edit.setObjectName("file_edit")
        self.horizontalLayout.addWidget(self.file_edit)
        self.file_picker_button = QtWidgets.QToolButton(self.widget)
        self.file_picker_button.setObjectName("file_picker_button")
        self.horizontalLayout.addWidget(self.file_picker_button)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.widget)
        self.samplerate_spinbox = QtWidgets.QComboBox(self.groupBox)
        self.samplerate_spinbox.setObjectName("samplerate_spinbox")
        self.samplerate_spinbox.addItem("")
        self.samplerate_spinbox.addItem("")
        self.samplerate_spinbox.addItem("")
        self.samplerate_spinbox.addItem("")
        self.samplerate_spinbox.addItem("")
        self.samplerate_spinbox.addItem("")
        self.samplerate_spinbox.addItem("")
        self.samplerate_spinbox.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.samplerate_spinbox)
        self.verticalLayout.addWidget(self.groupBox)
        self.widget_2 = QtWidgets.QWidget(AudioWriteDialog)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.widget_2)
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.verticalLayout_2.addWidget(self.commandLinkButton)
        self.progressBar = QtWidgets.QProgressBar(self.widget_2)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.verticalLayout.addWidget(self.widget_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(AudioWriteDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(AudioWriteDialog)
        self.buttonBox.accepted.connect(AudioWriteDialog.accept)
        self.buttonBox.rejected.connect(AudioWriteDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AudioWriteDialog)

    def retranslateUi(self, AudioWriteDialog):
        _translate = QtCore.QCoreApplication.translate
        AudioWriteDialog.setWindowTitle(_translate("AudioWriteDialog", "Create audio file"))
        self.textBrowser.setHtml(_translate("AudioWriteDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Generate audio file (mp3).</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- The currently loaded funscripts are used.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- For axes with no funscript, the value from the GUI is used. This includes calibration settings, transform, carrier, pulse settings and vibration.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- Output volume is determined by funscript. Volume controls and volume ramp does NOT work.</p></body></html>"))
        self.groupBox.setTitle(_translate("AudioWriteDialog", "Settings"))
        self.label.setText(_translate("AudioWriteDialog", "Media duration [s]"))
        self.label_2.setText(_translate("AudioWriteDialog", "Sample rate [samples/s]"))
        self.label_3.setText(_translate("AudioWriteDialog", "Output file (wav, mp3, ...)"))
        self.file_picker_button.setText(_translate("AudioWriteDialog", "..."))
        self.samplerate_spinbox.setItemText(0, _translate("AudioWriteDialog", "8000"))
        self.samplerate_spinbox.setItemText(1, _translate("AudioWriteDialog", "11025"))
        self.samplerate_spinbox.setItemText(2, _translate("AudioWriteDialog", "16000"))
        self.samplerate_spinbox.setItemText(3, _translate("AudioWriteDialog", "22050"))
        self.samplerate_spinbox.setItemText(4, _translate("AudioWriteDialog", "44100"))
        self.samplerate_spinbox.setItemText(5, _translate("AudioWriteDialog", "48000"))
        self.samplerate_spinbox.setItemText(6, _translate("AudioWriteDialog", "88200"))
        self.samplerate_spinbox.setItemText(7, _translate("AudioWriteDialog", "96000"))
        self.commandLinkButton.setText(_translate("AudioWriteDialog", "Create audio file"))
