# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\designer\funscriptconversiondialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FunscriptConversionDialog(object):
    def setupUi(self, FunscriptConversionDialog):
        FunscriptConversionDialog.setObjectName("FunscriptConversionDialog")
        FunscriptConversionDialog.resize(542, 429)
        self.gridLayout = QtWidgets.QGridLayout(FunscriptConversionDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_2 = QtWidgets.QWidget(FunscriptConversionDialog)
        self.widget_2.setObjectName("widget_2")
        self.formLayout = QtWidgets.QFormLayout(self.widget_2)
        self.formLayout.setContentsMargins(-1, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton)
        self.gridLayout.addWidget(self.widget_2, 3, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(FunscriptConversionDialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_funscript = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_funscript.setObjectName("lineEdit_funscript")
        self.gridLayout_3.addWidget(self.lineEdit_funscript, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.toolButton = QtWidgets.QToolButton(self.groupBox_2)
        self.toolButton.setObjectName("toolButton")
        self.gridLayout_3.addWidget(self.toolButton, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_alpha = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_alpha.setObjectName("lineEdit_alpha")
        self.gridLayout_3.addWidget(self.lineEdit_alpha, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEdit_beta = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_beta.setObjectName("lineEdit_beta")
        self.gridLayout_3.addWidget(self.lineEdit_beta, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(FunscriptConversionDialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.random_direction_change_probability = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.random_direction_change_probability.setDecimals(0)
        self.random_direction_change_probability.setMaximum(100.0)
        self.random_direction_change_probability.setProperty("value", 5.0)
        self.random_direction_change_probability.setObjectName("random_direction_change_probability")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.random_direction_change_probability)
        self.gridLayout.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(FunscriptConversionDialog)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.addWidget(self.textEdit)
        self.gridLayout.addWidget(self.groupBox, 4, 0, 1, 1)

        self.retranslateUi(FunscriptConversionDialog)
        QtCore.QMetaObject.connectSlotsByName(FunscriptConversionDialog)

    def retranslateUi(self, FunscriptConversionDialog):
        _translate = QtCore.QCoreApplication.translate
        FunscriptConversionDialog.setWindowTitle(_translate("FunscriptConversionDialog", "Funscript conversion - 1d to 2d"))
        self.pushButton.setText(_translate("FunscriptConversionDialog", "Convert"))
        self.groupBox_2.setTitle(_translate("FunscriptConversionDialog", "Files"))
        self.label.setText(_translate("FunscriptConversionDialog", "Funscript"))
        self.toolButton.setText(_translate("FunscriptConversionDialog", "..."))
        self.label_2.setText(_translate("FunscriptConversionDialog", "Alpha axis"))
        self.label_3.setText(_translate("FunscriptConversionDialog", "Beta axis"))
        self.groupBox_3.setTitle(_translate("FunscriptConversionDialog", "Options"))
        self.label_4.setText(_translate("FunscriptConversionDialog", "Random direction change probability"))
        self.random_direction_change_probability.setSuffix(_translate("FunscriptConversionDialog", "%"))
        self.groupBox.setTitle(_translate("FunscriptConversionDialog", "log"))
