# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\designer\funscriptconversiondialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FunscriptConversionDialog(object):
    def setupUi(self, FunscriptConversionDialog):
        FunscriptConversionDialog.setObjectName("FunscriptConversionDialog")
        FunscriptConversionDialog.resize(543, 284)
        self.gridLayout = QtWidgets.QGridLayout(FunscriptConversionDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(FunscriptConversionDialog)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textEdit = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.addWidget(self.textEdit)
        self.gridLayout.addWidget(self.groupBox, 3, 0, 1, 1)
        self.widget = QtWidgets.QWidget(FunscriptConversionDialog)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_funscript = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_funscript.setObjectName("lineEdit_funscript")
        self.gridLayout_2.addWidget(self.lineEdit_funscript, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.toolButton = QtWidgets.QToolButton(self.widget)
        self.toolButton.setObjectName("toolButton")
        self.gridLayout_2.addWidget(self.toolButton, 0, 2, 1, 1)
        self.lineEdit_beta = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_beta.setObjectName("lineEdit_beta")
        self.gridLayout_2.addWidget(self.lineEdit_beta, 2, 1, 1, 1)
        self.lineEdit_alpha = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_alpha.setObjectName("lineEdit_alpha")
        self.gridLayout_2.addWidget(self.lineEdit_alpha, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(FunscriptConversionDialog)
        self.widget_2.setObjectName("widget_2")
        self.formLayout = QtWidgets.QFormLayout(self.widget_2)
        self.formLayout.setContentsMargins(-1, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton)
        self.gridLayout.addWidget(self.widget_2, 2, 0, 1, 1)

        self.retranslateUi(FunscriptConversionDialog)
        QtCore.QMetaObject.connectSlotsByName(FunscriptConversionDialog)

    def retranslateUi(self, FunscriptConversionDialog):
        _translate = QtCore.QCoreApplication.translate
        FunscriptConversionDialog.setWindowTitle(_translate("FunscriptConversionDialog", "Funscript conversion - 1d to 2d"))
        self.groupBox.setTitle(_translate("FunscriptConversionDialog", "log"))
        self.label.setText(_translate("FunscriptConversionDialog", "Funscript"))
        self.label_2.setText(_translate("FunscriptConversionDialog", "Alpha axis"))
        self.toolButton.setText(_translate("FunscriptConversionDialog", "..."))
        self.label_3.setText(_translate("FunscriptConversionDialog", "Beta axis"))
        self.pushButton.setText(_translate("FunscriptConversionDialog", "Convert"))
