# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\designer\volumecontrolwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VolumeControlForm(object):
    def setupUi(self, VolumeControlForm):
        VolumeControlForm.setObjectName("VolumeControlForm")
        VolumeControlForm.resize(400, 300)
        self.horizontalLayout = QtWidgets.QHBoxLayout(VolumeControlForm)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(VolumeControlForm)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_volume = QtWidgets.QLabel(self.groupBox)
        self.label_volume.setObjectName("label_volume")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_volume)
        self.doubleSpinBox_volume = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_volume.setDecimals(2)
        self.doubleSpinBox_volume.setMaximum(100.0)
        self.doubleSpinBox_volume.setSingleStep(0.1)
        self.doubleSpinBox_volume.setProperty("value", 100.0)
        self.doubleSpinBox_volume.setObjectName("doubleSpinBox_volume")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_volume)
        self.label_target_volume = QtWidgets.QLabel(self.groupBox)
        self.label_target_volume.setObjectName("label_target_volume")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_target_volume)
        self.doubleSpinBox_target_volume = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_target_volume.setMaximum(100.0)
        self.doubleSpinBox_target_volume.setSingleStep(0.1)
        self.doubleSpinBox_target_volume.setProperty("value", 100.0)
        self.doubleSpinBox_target_volume.setObjectName("doubleSpinBox_target_volume")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_target_volume)
        self.label_rate = QtWidgets.QLabel(self.groupBox)
        self.label_rate.setObjectName("label_rate")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_rate)
        self.doubleSpinBox_rate = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_rate.setMaximum(10000.0)
        self.doubleSpinBox_rate.setSingleStep(0.1)
        self.doubleSpinBox_rate.setProperty("value", 5.0)
        self.doubleSpinBox_rate.setObjectName("doubleSpinBox_rate")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_rate)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label)
        self.radioButton_enabled = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_enabled.setText("")
        self.radioButton_enabled.setObjectName("radioButton_enabled")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.radioButton_enabled)
        self.horizontalLayout.addWidget(self.groupBox)

        self.retranslateUi(VolumeControlForm)
        QtCore.QMetaObject.connectSlotsByName(VolumeControlForm)

    def retranslateUi(self, VolumeControlForm):
        _translate = QtCore.QCoreApplication.translate
        VolumeControlForm.setWindowTitle(_translate("VolumeControlForm", "Form"))
        self.groupBox.setTitle(_translate("VolumeControlForm", "Volume control and ramp"))
        self.label_volume.setText(_translate("VolumeControlForm", "Volume [%]"))
        self.label_target_volume.setText(_translate("VolumeControlForm", "Target volume [%]"))
        self.label_rate.setText(_translate("VolumeControlForm", "Rate [% / min]"))
        self.label.setText(_translate("VolumeControlForm", "Enable"))
