on:
  workflow_dispatch:

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.11'
          python_arch: 'x86'
          spec: 'restim.spec'
          requirements: 'requirements.txt'
          upload_exe_with_name: 'restim-32.exe'

          
